<?php

return $clients = [
    [
        "id" => 0,
        "userId" => 0,
        "name" => "TechStart SRL",
        "email" => "info@techstart.it",
        "phone" => "+39 02 5551234",
        "company" => "TechStart SRL",
        "address" => "Via Innovazione 10, Milano",
        "vatNumber" => "IT11111111111",
        "createdAt" => "2024-01-15",
    ],
    [
        "id" => 1,
        "userId" => 0,
        "name" => "Ristorante Da Luigi",
        "email" => "luigi@ristorantedaluigi.it",
        "phone" => "+39 02 5559876",
        "company" => "Da Luigi SAS",
        "address" => "Corso Buenos Aires 88, Milano",
        "createdAt" => "2024-02-20",
    ],
    [
        "id" => 2,
        "userId" => 0,
        "name" => "Studio Legale Bianchi",
        "email" => "avv.bianchi@studiobianchi.it",
        "phone" => "+39 02 5554567",
        "company" => "Studio Legale Bianchi & Associati",
        "address" => "Via Montenapoleone 5, Milano",
        "vatNumber" => "IT22222222222",
        "createdAt" => "2024-03-10",
    ],
    [
        "id" => 3,
        "userId" => 1,
        "name" => "Famiglia Verdi",
        "email" => "mario.verdi@email.it",
        "phone" => "+39 011 3331234",
        "address" => "Via delle Rose 15, Torino",
        "createdAt" => "2024-01-20",
    ],
    [
        "id" => 4,
        "userId" => 1,
        "name" => "Condominio Aurora",
        "email" => "admin@condominioaurora.it",
        "phone" => "+39 011 3339999",
        "company" => "Condominio Aurora",
        "address" => "Corso Francia 200, Torino",
        "createdAt" => "2024-02-05",
    ],
    [
        "id" => 5,
        "userId" => 1,
        "name" => "Hotel Bellavista",
        "email" => "direzione@hotelbellavista.it",
        "phone" => "+39 011 3337777",
        "company" => "Bellavista Hotels SPA",
        "address" => "Piazza Castello 10, Torino",
        "vatNumber" => "IT33333333333",
        "createdAt" => "2024-03-15",
    ],
    [
        "id" => 6,
        "userId" => 2,
        "name" => "Startup Innovate",
        "email" => "ceo@startupinnovate.it",
        "phone" => "+39 055 7771234",
        "company" => "Startup Innovate SRL",
        "address" => "Via dei Calzaiuoli 23, Firenze",
        "vatNumber" => "IT44444444444",
        "createdAt" => "2024-01-25",
    ],
    [
        "id" => 7,
        "userId" => 2,
        "name" => "Azienda Tradizione",
        "email" => "info@tradizione.it",
        "phone" => "+39 055 7778888",
        "company" => "Tradizione SPA",
        "address" => "Lungarno Corsini 5, Firenze",
        "vatNumber" => "IT55555555555",
        "createdAt" => "2024-02-10",
    ],
    [
        "id" => 8,
        "userId" => 2,
        "name" => "PMI Solutions",
        "email" => "direzione@pmisolutions.it",
        "phone" => "+39 055 7776666",
        "company" => "PMI Solutions SRL",
        "address" => "Via Tornabuoni 18, Firenze",
        "vatNumber" => "IT66666666666",
        "createdAt" => "2024-03-01",
    ]
];
