<?php

return $quotes = [
    [
        "id" => 0,
        "userId" => 0,
        "clientId" => 0,
        "clientName" => "TechStart SRL",
        "number" => "PRV-2024-001",
        "status" => "accepted",
        "items" => [
            ["serviceId" => 1, "serviceName" => "E-commerce", "quantity" => 1, "unitPrice" => 5000, "unit" => "progetto", "discount" => 0, "total" => 5000],
            ["serviceId" => 3, "serviceName" => "Logo Design", "quantity" => 1, "unitPrice" => 800, "unit" => "progetto", "discount" => 0, "total" => 800],
            ["serviceId" => 5, "serviceName" => "SEO Setup", "quantity" => 1, "unitPrice" => 1200, "unit" => "progetto", "discount" => 10, "total" => 1080],
        ],
        "subtotal" => 7000,
        "discountPercent" => 5,
        "discountAmount" => 344,
        "taxPercent" => 22,
        "taxAmount" => 1464.32,
        "total" => 8120.32,
        "notes" => "Progetto completo e-commerce con branding e ottimizzazione SEO.",
        "validUntil" => "2024-04-15",
        "createdAt" => "2024-03-01",
        "updatedAt" => "2024-03-05",
    ],
    [
        "id" => 1,
        "userId" => 0,
        "clientId" => 1,
        "clientName" => "Ristorante Da Luigi",
        "number" => "PRV-2024-002",
        "status" => "sent",
        "items" => [
            ["serviceId" => 0, "serviceName" => "Sito Web Vetrina", "quantity" => 1, "unitPrice" => 2500, "unit" => "progetto", "discount" => 0, "total" => 2500],
            ["serviceId" => 7, "serviceName" => "Social Media Management", "quantity" => 6, "unitPrice" => 500, "unit" => "mese", "discount" => 0, "total" => 3000],
        ],
        "subtotal" => 5500,
        "discountPercent" => 0,
        "discountAmount" => 0,
        "taxPercent" => 22,
        "taxAmount" => 1210,
        "total" => 6710,
        "notes" => "Sito vetrina con menu digitale e gestione social 6 mesi.",
        "validUntil" => "2024-04-20",
        "createdAt" => "2024-03-10",
        "updatedAt" => "2024-03-10",
    ],
    [
        "id" => 2,
        "userId" => 0,
        "clientId" => 2,
        "clientName" => "Studio Legale Bianchi",
        "number" => "PRV-2024-003",
        "status" => "draft",
        "items" => [
            ["serviceId" => 0, "serviceName" => "Sito Web Vetrina", "quantity" => 1, "unitPrice" => 2500, "unit" => "progetto", "discount" => 0, "total" => 2500],
        ],
        "subtotal" => 2500,
        "discountPercent" => 0,
        "discountAmount" => 0,
        "taxPercent" => 22,
        "taxAmount" => 550,
        "total" => 3050,
        "validUntil" => "2024-04-30",
        "createdAt" => "2024-03-15",
        "updatedAt" => "2024-03-15",
    ],
    [
        "id" => 3,
        "userId" => 1,
        "clientId" => 3,
        "clientName" => "Famiglia Verdi",
        "number" => "PRV-2024-001",
        "status" => "accepted",
        "items" => [
            ["serviceId" => 11, "serviceName" => "Demolizione", "quantity" => 25, "unitPrice" => 35, "unit" => "mq", "discount" => 0, "total" => 875],
            ["serviceId" => 12, "serviceName" => "Costruzione Muri", "quantity" => 18, "unitPrice" => 85, "unit" => "mq", "discount" => 0, "total" => 1530],
            ["serviceId" => 16, "serviceName" => "Posa Pavimento", "quantity" => 45, "unitPrice" => 40, "unit" => "mq", "discount" => 0, "total" => 1800],
            ["serviceId" => 17, "serviceName" => "Tinteggiatura", "quantity" => 120, "unitPrice" => 12, "unit" => "mq", "discount" => 0, "total" => 1440],
        ],
        "subtotal" => 5645,
        "discountPercent" => 5,
        "discountAmount" => 282.25,
        "taxPercent" => 10,
        "taxAmount" => 536.28,
        "total" => 5899.03,
        "notes" => "Ristrutturazione completa appartamento 45mq. Materiali inclusi.",
        "validUntil" => "2024-04-10",
        "createdAt" => "2024-02-20",
        "updatedAt" => "2024-02-25",
    ],
    [
        "id" => 4,
        "userId" => 1,
        "clientId" => 4,
        "clientName" => "Condominio Aurora",
        "number" => "PRV-2024-002",
        "status" => "sent",
        "items" => [
            ["serviceId" => 3, "serviceName" => "Intonacatura", "quantity" => 500, "unitPrice" => 25, "unit" => "mq", "discount" => 10, "total" => 11250],
            ["serviceId" => 7, "serviceName" => "Tinteggiatura", "quantity" => 500, "unitPrice" => 12, "unit" => "mq", "discount" => 10, "total" => 5400],
        ],
        "subtotal" => 18500,
        "discountPercent" => 0,
        "discountAmount" => 0,
        "taxPercent" => 10,
        "taxAmount" => 1665,
        "total" => 18315,
        "notes" => "Rifacimento facciata condominiale. Ponteggi inclusi.",
        "validUntil" => "2024-05-01",
        "createdAt" => "2024-03-05",
        "updatedAt" => "2024-03-05",
    ],
    [
        "id" => 5,
        "userId" => 1,
        "clientId" => 5,
        "clientName" => "Hotel Bellavista",
        "number" => "PRV-2024-003",
        "status" => "rejected",
        "items" => [
            ["serviceId" => 4, "serviceName" => "Impianto Elettrico", "quantity" => 80, "unitPrice" => 45, "unit" => "punto", "discount" => 0, "total" => 3600],
            ["serviceId" => 5, "serviceName" => "Impianto Idraulico", "quantity" => 40, "unitPrice" => 120, "unit" => "punto", "discount" => 0, "total" => 4800],
        ],
        "subtotal" => 8400,
        "discountPercent" => 8,
        "discountAmount" => 672,
        "taxPercent" => 10,
        "taxAmount" => 772.80,
        "total" => 8500.80,
        "notes" => "Rifacimento impianti piano terra.",
        "validUntil" => "2024-03-20",
        "createdAt" => "2024-02-15",
        "updatedAt" => "2024-03-01",
    ],
    [
        "id" => 6,
        "userId" => 2,
        "clientId" => 6,
        "clientName" => "Startup Innovate",
        "number" => "PRV-2024-001",
        "status" => "accepted",
        "items" => [
            ["serviceId" => 14, "serviceName" => "Business Plan", "quantity" => 1, "unitPrice" => 2000, "unit" => "progetto", "discount" => 0, "total" => 2000],
            ["serviceId" => 15, "serviceName" => "Analisi di Mercato", "quantity" => 1, "unitPrice" => 1500, "unit" => "progetto", "discount" => 0, "total" => 1500],
            ["serviceId" => 16, "serviceName" => "Consulenza Oraria", "quantity" => 10, "unitPrice" => 120, "unit" => "ora", "discount" => 0, "total" => 1200],
        ],
        "subtotal" => 4700,
        "discountPercent" => 10,
        "discountAmount" => 470,
        "taxPercent" => 22,
        "taxAmount" => 930.60,
        "total" => 5160.60,
        "notes" => "Pacchetto startup completo per round di finanziamento.",
        "validUntil" => "2024-04-01",
        "createdAt" => "2024-02-28",
        "updatedAt" => "2024-03-02",
    ],
    [
        "id" => 7,
        "userId" => 2,
        "clientId" => 7,
        "clientName" => "Azienda Tradizione",
        "number" => "PRV-2024-002",
        "status" => "sent",
        "items" => [
            ["serviceId" => 17, "serviceName" => "Workshop Aziendale", "quantity" => 3, "unitPrice" => 1800, "unit" => "giorno", "discount" => 0, "total" => 5400],
            ["serviceId" => 18, "serviceName" => "Coaching Executive", "quantity" => 12, "unitPrice" => 200, "unit" => "sessione", "discount" => 0, "total" => 2400],
        ],
        "subtotal" => 7800,
        "discountPercent" => 0,
        "discountAmount" => 0,
        "taxPercent" => 22,
        "taxAmount" => 1716,
        "total" => 9516,
        "notes" => "Programma formazione management aziendale.",
        "validUntil" => "2024-04-15",
        "createdAt" => "2024-03-08",
        "updatedAt" => "2024-03-08",
    ],
    [
        "id" => 8,
        "userId" => 2,
        "clientId" => 8,
        "clientName" => "PMI Solutions",
        "number" => "PRV-2024-003",
        "status" => "draft",
        "items" => [
            ["serviceId" => 19, "serviceName" => "Budget Previsionale", "quantity" => 1, "unitPrice" => 2500, "unit" => "progetto", "discount" => 0, "total" => 2500],
            ["serviceId" => 20, "serviceName" => "Controllo di Gestione", "quantity" => 1, "unitPrice" => 3000, "unit" => "progetto", "discount" => 0, "total" => 3000],
        ],
        "subtotal" => 5500,
        "discountPercent" => 5,
        "discountAmount" => 275,
        "taxPercent" => 22,
        "taxAmount" => 1149.50,
        "total" => 6374.50,
        "notes" => "Setup completo sistema controllo gestione.",
        "validUntil" => "2024-04-30",
        "createdAt" => "2024-03-12",
        "updatedAt" => "2024-03-12",
    ]
];
